#!/bin/bash

disp=xrandr | egrep " connected " | cut -d' ' -f1
# if user enters a number...
if [ ! -z `echo $1 | egrep "^[0-9]+$"` ]
then
    # if user enters a number between 0 and 1
    if [ "$1" -gt 0 ] && [ "$1" -lt 1 ]
    then
        xrandr --output "$disp" --brightness "$1"
    else
        echo "brightness must be between 0 and 1"
    fi
else
    echo "$0: Usage: xlbright <number between 0 and 1>"
fi
